AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy S3 Buckets for MeetingNotesApp

Resources:
  MeetingNotesAppAPIBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub meetingnotesapp-api-${AWS::AccountId}-${AWS::Region}
      AccessControl: Private

  MeetingNotesAppFrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub meetingnotesapp-frontend-${AWS::AccountId}-${AWS::Region}
      AccessControl: Private

Outputs:
  S3APIBucketName:
    Description: Name of the S3 bucket for the API
    Value: !Ref MeetingNotesAppAPIBucket

  S3FrontendBucketName:
    Description: Name of the S3 bucket for the Frontend
    Value: !Ref MeetingNotesAppFrontendBucket
