AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy MeetingNotesApp with Node.js Backend, React Frontend, PostgreSQL RDS, and S3 Bucket

Parameters:
  VpcCIDR:
    Type: String
    Default: '10.0.0.0/16'
    Description: CIDR block for the VPC
  KeyName:
    Description: Name of an existing EC2 keypair to enable SSH access to the instance.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 keypair.
  DBMasterUsername:
    Description: Master username for the RDS instance
    Type: String
  DBMasterUserPassword:
    Description: Master user password for the RDS instance
    Type: String
    NoEcho: true
  GitHubRepository:
    Description: GitHub repository URL where the Node.js backend and React frontend code reside
    Type: String
    Default: 'https://github.com/MeetingNotes/MeetiningNotesApp'
  AllowedIP:
    Description: The IP address range that can access RDS and EC2 instances
    Type: String
    Default: '0.0.0.0/0'
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.

Resources:      
  MeetingNotesAppAPIBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub meetingnotesapp-api-${AWS::AccountId}-${AWS::Region}
      AccessControl: Private
      
  MeetingNotesAppFrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub meetingnotesapp-frontend-${AWS::AccountId}-${AWS::Region}
      AccessControl: Private
